#!/usr/bin/lua


---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/14/24 5:37 PM
---
local tf  = require "tf_module"

local cmdtype = " get"
cmd = ""
cmd = "hwsys_ctrl " .. "SHT_TEMPERATURE" .. cmdtype
local temperature = tf.executeCommand(cmd)
print("temperature = " .. temperature)
