#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 4/11/24 9:48 AM
---

--local tf        = require "tf_module"
--local utilities = require "tf_utilities"
--local sht       = require "hw_sensor_module"

local i2c_module = {}

i2c_module.inputStatus_list =
{
    "inputTamper",
    "inputSensor1",
    "inputSensor2",
    --"inputRelay1",
}



function i2c_module.get_sensorsData()
    local res = {}
    for key, func in pairs(hw_sysEnum.sensors) do
        print("key = " .. key)
        res[key] = func(0, key)
    end
    return res
end

return i2c_module
