---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 4/18/24 10:38 AM
---

local snmp_base = {}

snmp_base.requestType = {
    ["-g"] = "GET",
    ["-n"] = "GET_NEXT",
    ["-s"] = "SET"
}

snmp_base.autoRestartEntry = {
    { "1.3.6.1.4.1.42019.3.2.1.2.1.1.1", "autoRstIndex",            nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.1.2.1.1.2", "autoRstMode",             nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.1.2.1.1.3", "autoRstDstIP",            nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.1.2.1.1.4", "autoRstSpeedDown",        nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.1.2.1.1.5", "autoRstSpeedUp",          nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.1.2.1.1.6", "autoReStartTimeOnHour",   nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.1.2.1.1.7", "autoReStartTimeOnMin",    nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.1.2.1.1.8", "autoReStartTimeOffHour",  nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.1.2.1.1.9", "autoReStartTimeOffMin",   nil, "column" },
}

snmp_base.portPoeEntry = {
    { "1.3.6.1.4.1.42019.3.2.1.3.1.1.1", "portPoeIndex", nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.1.3.1.1.2", "portPoeState", nil, "column" },
}

snmp_base.inputStatusEntry = {
    { "1.3.6.1.4.1.42019.3.2.2.2.1.1.1", "inputIndex", nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.2.1.1.2", "inputType",  nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.2.1.1.3", "inputState", nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.2.1.1.4", "inputAlarm", nil, "column" },
}

snmp_base.poeStatusEntry = {
    { "1.3.6.1.4.1.42019.3.2.2.5.1.1.1", "portPoeStatusIndex", nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.5.1.1.2", "portPoeStatusState", nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.5.1.1.3", "portPoeStatusPower", nil, "column" },
}

snmp_base.autoRestartErrorsEntry = {
    { "1.3.6.1.4.1.42019.3.2.2.6.1.1.1.1", "arPortIndex",  nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.6.1.1.1.2", "arPortStatus", nil, "column" },
}

snmp_base.sfpStatusEntry = {
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.1", "portSfpIndex",          nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.2", "portSfpPresent",        nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.3", "portSfpSignalDetect",   nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.4", "portSfpVendor",         nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.5", "portSfpOui",            nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.6", "portSfpPartNumber",     nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.7", "portSfpRevision",       nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.8", "portSfpTemperature",    nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.9", "portSfpVoltage",        nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.10", "portSfpBiasCurrent",   nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.11", "portSfpTxOutPower",    nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.12", "portSfpTxOutPowerDb",  nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.13", "portSfpRxOutPower",    nil, "column" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1.14", "portSfpRxOutPowerDb",  nil, "column" },
}

snmp_base.oid_Entry = {
    { "1.3.6.1.4.1.42019.3.2.1.1.2.1",   "comfStartEntry",          nil,                              "not_defined" },
    { "1.3.6.1.4.1.42019.3.2.1.2.1.1",   "autoRestartEntry",        snmp_base.autoRestartEntry,       "row" },
    { "1.3.6.1.4.1.42019.3.2.1.3.1.1",   "portPoeEntry",            snmp_base.portPoeEntry,           "row" },
    { "1.3.6.1.4.1.42019.3.2.2.2.1.1",   "inputStatusEntry",        snmp_base.inputStatusEntry,       "row" },
    { "1.3.6.1.4.1.42019.3.2.2.5.1.1",   "poeStatusEntry",          snmp_base.poeStatusEntry,         "row" },
    { "1.3.6.1.4.1.42019.3.2.2.6.1.1.1", "autoRestartErrorsEntry",  snmp_base.autoRestartErrorsEntry, "row" },
    { "1.3.6.1.4.1.42019.3.2.2.6.2.1.1", "comfortStartStatusEntry", nil,                              "not_defined" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1.1",   "sfpStatusEntry",          snmp_base.sfpStatusEntry,         "row"       }
}

snmp_base.oid_table =
{
    { "1.3.6.1.4.1.42019.3.2.1.1.2",   "comfStartTable",          nil,                    "not_defined" },
    { "1.3.6.1.4.1.42019.3.2.1.2.1",   "autoRestartTable",        snmp_base.oid_Entry[2], "entry"       },
    { "1.3.6.1.4.1.42019.3.2.1.3.1",   "portPoeTable",            snmp_base.oid_Entry[3], "entry"       },
    { "1.3.6.1.4.1.42019.3.2.2.2.1",   "inputStatusTable",        snmp_base.oid_Entry[4], "entry"       },
    { "1.3.6.1.4.1.42019.3.2.2.5.1",   "poeStatusTable",          snmp_base.oid_Entry[5], "entry"       },
    { "1.3.6.1.4.1.42019.3.2.2.6.1.1", "autoRestartErrorsTable",  snmp_base.oid_Entry[6], "entry"       },
    { "1.3.6.1.4.1.42019.3.2.2.6.2.1", "comfortStartStatusTable", nil,                    "not_defined" },
    { "1.3.6.1.4.1.42019.3.2.2.7.1",   "sfpStatusTable",          snmp_base.oid_Entry[8], "entry"       },
}

snmp_base.fwStatusList = {
    { "1.3.6.1.4.1.42019.3.2.2.3.1", "fwVersion", nil, "scalar" },
}

snmp_base.specialStatus_list = {
    { "1.3.6.1.4.1.42019.3.2.2.6.1", "autoRestartErrors", snmp_base.oid_table[6], "table" },
}

snmp_base.upsStatusList = {
    { "1.3.6.1.4.1.42019.3.2.2.1.1", "upsModeAvalible",     nil, "scalar" },
    { "1.3.6.1.4.1.42019.3.2.2.1.2", "upsPwrSource",        nil, "scalar" },
    { "1.3.6.1.4.1.42019.3.2.2.1.3", "upsBatteryVoltage",   nil, "scalar" },
    { "1.3.6.1.4.1.42019.3.2.2.1.4", "upsBatteryTime",      nil, "scalar" },
}

snmp_base.sensorList = {
    { "1.3.6.1.4.1.42019.3.2.2.8.1", "sensorConnected",      nil, "scalar" },
    { "1.3.6.1.4.1.42019.3.2.2.8.2", "sensorTemperature",    nil, "scalar" },
    { "1.3.6.1.4.1.42019.3.2.2.8.3", "sensorHumidity",       nil, "scalar" },
    { "1.3.6.1.4.1.42019.3.2.2.8.4", "sensorTemperatureMin", nil, "scalar" },
    { "1.3.6.1.4.1.42019.3.2.2.8.5", "sensorTemperatureMax", nil, "scalar" },
    { "1.3.6.1.4.1.42019.3.2.2.8.6", "sensorHumidityMin",    nil, "scalar" },
    { "1.3.6.1.4.1.42019.3.2.2.8.7", "sensorHumidityMax",    nil, "scalar" },
}

snmp_base.configPSW_list = {
    {"1.3.6.1.4.1.42019.3.2.1.1", "comfortStart",   nil,                    "not_defined" },
    {"1.3.6.1.4.1.42019.3.2.1.2", "autoRestart",    snmp_base.oid_table[2], "table" },
    {"1.3.6.1.4.1.42019.3.2.1.3", "portPoe",        snmp_base.oid_table[3], "table" },
    {"1.3.6.1.4.1.42019.3.2.1.4", "outStatePSW",    nil,                    "scalar" },
}

snmp_base.statusPSW_list = {
    { "1.3.6.1.4.1.42019.3.2.2.1",  "upsStatus",        snmp_base.upsStatusList,        "list" },
    { "1.3.6.1.4.1.42019.3.2.2.2",  "inputStatus",      snmp_base.oid_table[4],         "table" },
    { "1.3.6.1.4.1.42019.3.2.2.3",  "fwStatus",         snmp_base.fwStatusList,         "list" },
    { "1.3.6.1.4.1.42019.3.2.2.4",  "empty",            nil,                            "not_defined" },
    { "1.3.6.1.4.1.42019.3.2.2.5",  "poeStatus",        snmp_base.oid_table[5],         "table" },
    { "1.3.6.1.4.1.42019.3.2.2.6",  "specialStatus",    snmp_base.specialStatus_list,   "list" },
    { "1.3.6.1.4.1.42019.3.2.2.7",  "sfpStatus",        snmp_base.oid_table[8],         "table" },
    { "1.3.6.1.4.1.42019.3.2.2.8",  "sensorEntry",      snmp_base.sensorList,           "list" },
}

snmp_base.psw_list = {
    { "1.3.6.1.4.1.42019.3.2.1", "configPSW", snmp_base.configPSW_list, "list" },
    { "1.3.6.1.4.1.42019.3.2.2", "statusPSW", snmp_base.statusPSW_list, "list" },
}

snmp_base.switch_list = {
    {  "1.3.6.1.4.1.42019.3.1", "empty", nil,                "not_defined" },
    {  "1.3.6.1.4.1.42019.3.2", "psw",   snmp_base.psw_list, "list" }     -- obj 2
}

snmp_base.main_list = {
    { "1.3.6.1.4.1.42019.1", "empty",           nil,                    "not_defined" },  -- obj 1
    { "1.3.6.1.4.1.42019.2", "empty",           nil,                    "not_defined" },  -- obj 1
    { "1.3.6.1.4.1.42019.3", "switch",          snmp_base.switch_list,  "list" },  -- obj 1
    { "1.3.6.1.4.1.42019.4", "integrations",    nil,                    "not_defined" }
}

snmp_base.mib_list =
{
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.12"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpTxOutPowerDb",
    },
    ["1.3.6.1.4.1.42019.3.2.1.2.1.1.3"] =
    {
        valueType = "IpAddress",
        nodetype = "column",
        oidLength = "7",
        ubusType = "ar_config",
        i2c_addr = "0",
        isZero = "no",
        name = "autoRstDstIP",
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1"] =
    {
        nodetype = "table",
        oidLength = "5",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "sfpStatusTable",
    },
    ["1.3.6.1.4.1.42019.3.2.2.1.3"] =
    {
        valueType = "INTEGER",
        nodetype = "scalar",
        oidLength = "5",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "upsBatteryVoltage",
    },
    ["1.3.6.1.4.1.42019.4.2.2"] =
    {
        oidLength = "3",
        ubusType = "nd",
        i2c_addr = "0",
        name = "inputTeleport",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.6.1"] =
    {
        oidLength = "5",
        ubusType = "nd",
        i2c_addr = "0",
        name = "autoRestartErrors",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.2.5.1.1.2"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "yes",
        enum  = {
            up = "1",
            down = "2",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "poe_status",
        name = "portPoeStatusState",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.10"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpBiasCurrent",
    },
    ["1.3.6.1.4.1.42019.3.2.2"] =
    {
        oidLength = "3",
        ubusType = "nd",
        i2c_addr = "0",
        name = "statusPSW",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.2.6.1.1"] =
    {
        nodetype = "table",
        oidLength = "6",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "autoRestartErrorsTable",
    },
    ["1.3.6.1.4.1.42019.3.2.2.2.1"] =
    {
        nodetype = "table",
        oidLength = "5",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "inputStatusTable",
    },
    ["1.3.6.1.4.1.42019.3.2.1.1.2"] =
    {
        nodetype = "table",
        oidLength = "5",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "comfStartTable",
    },
    ["1.3.6.1.4.1.42019.3.2.2.6"] =
    {
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        name = "specialStatus",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.1.3.1.1.2"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "yes",
        enum  = {
            enabled = "1",
            disabled = "2",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "poe_config",
        name = "portPoeState",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.1.2"] =
    {
        nodetype = "scalar",
        oidLength = "5",
        isEnum = "yes",
        enum  = {
            ac = "2",
            battery = "1",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "i2c",
        name = "upsPwrSource",
        isZero = "isZero",
    },
    ["1.3.6.1.4.1.42019.3.2.2.3.1"] =
    {
        valueType = "OCTET STRING",
        nodetype = "scalar",
        oidLength = "5",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "fwVersion",
    },
    ["1.3.6.1.4.1.42019.4.2.2.1.1.2"] =
    {
        nodetype = "column",
        oidLength = "6",
        isEnum = "yes",
        enum  = {
            short = "2",
            open = "1",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "nd",
        name = "inputStateTLP",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.3"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpSignalDetect",
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpIndex",
    },
    ["1.3.6.1.4.1.42019.3.2.1.3.1.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "portPoeIndex",
    },
    ["1.3.6.1.4.1.42019.3.2.2.8.3"] =
    {
        valueType = "INTEGER",
        nodetype = "scalar",
        oidLength = "5",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "sensorHumidity",
    },
    ["1.3.6.1.4.1.42019.4.2.4"] =
    {
        oidLength = "3",
        ubusType = "nd",
        i2c_addr = "0",
        name = "fwStatusTLP",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.4.2"] =
    {
        oidLength = "2",
        ubusType = "nd",
        i2c_addr = "0",
        name = "teleport",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.1.3"] =
    {
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        name = "portPoe",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.2.2"] =
    {
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        name = "inputStatus",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.1"] =
    {
        oidLength = "3",
        ubusType = "nd",
        i2c_addr = "0",
        name = "configPSW",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.2.5"] =
    {
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        name = "poeStatus",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.1.2.1.1.5"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "ar_config",
        i2c_addr = "0",
        isZero = "no",
        name = "autoRstSpeedUp",
    },
    ["1.3.6.1.4.1.42019.3.2.2.1.1"] =
    {
        nodetype = "scalar",
        oidLength = "5",
        isEnum = "yes",
        enum  = {
            on = "1",
            off = "2",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "i2c",
        name = "upsModeAvalible",
        isZero = "isZero",
    },
    ["1.3.6.1.4.1.42019.3.2.1.1"] =
    {
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        name = "comfortStart",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.6"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "no",
        i2c_addr = "0",
        valueType = "DisplayString",
        ubusType = "i2c",
        name = "portSfpPartNumber",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.1.4.1"] =
    {
        nodetype = "scalar",
        oidLength = "5",
        isEnum = "yes",
        enum  = {
            short = "2",
            open = "1",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "nd",
        name = "state",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.7"] =
    {
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        name = "sfpStatus",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.9"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpVoltage",
    },
    ["1.3.6.1.4.1.42019.3.2.1.1.2.1"] =
    {
        nodetype = "row",
        oidLength = "6",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "comfStartEntry",
    },
    ["1.3.6.1.4.1.42019.3.2.2.2.1.1.4"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "yes",
        enum  = {
            any = "3",
            short = "1",
            open = "2",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "i2c",
        name = "inputAlarm",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.1.2.1.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "ar_config",
        i2c_addr = "0",
        isZero = "no",
        name = "autoRstIndex",
    },
    ["1.3.6.1.4.1.42019.4.2.2.1.1"] =
    {
        nodetype = "row",
        oidLength = "5",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "inputStatusEntryTLP",
    },
    ["1.3.6.1.4.1.42019.3.2.1.2.1.1"] =
    {
        nodetype = "row",
        oidLength = "6",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "autoRestartEntry",
    },
    ["1.3.6.1.4.1.42019.3.2.2.5.1"] =
    {
        nodetype = "table",
        oidLength = "5",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "poeStatusTable",
    },
    ["1.3.6.1.4.1.42019.3.2.2.6.1.1.1.2"] =
    {
        nodetype = "column",
        oidLength = "8",
        isEnum = "yes",
        enum  = {
            noLink = "2",
            normal = "1",
            noPing = "3",
            lowSpeed = "4",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "ar_status",
        name = "arPortStatus",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.1.3.1.1"] =
    {
        nodetype = "row",
        oidLength = "6",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "portPoeEntry",
    },
    ["1.3.6.1.4.1.42019.4.2.4.1"] =
    {
        valueType = "OCTET STRING",
        nodetype = "scalar",
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "fwVersionTLP",
    },
    ["1.3.6.1.4.1.42019.3.2.1.3.1"] =
    {
        nodetype = "table",
        oidLength = "5",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "portPoeTable",
    },
    ["1.3.6.1.4.1.42019.4.2.2.1.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "6",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "inputIndexTLP",
    },
    ["1.3.6.1.4.1.42019.4"] =
    {
        oidLength = "1",
        ubusType = "nd",
        i2c_addr = "0",
        name = "integrations",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.6.1.1.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "8",
        ubusType = "ar_status",
        i2c_addr = "0",
        isZero = "ar_status",
        name = "arPortIndex",
    },
    ["1.3.6.1.4.1.42019.3.2.2.2.1.1.3"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "yes",
        enum  = {
            short = "1",
            open = "2",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "i2c",
        name = "inputState",
        isZero = "isZero",
    },
    ["1.3.6.1.4.1.42019.4.2.3.1.1.2"] =
    {
        nodetype = "column",
        oidLength = "6",
        isEnum = "yes",
        enum  = {
            short = "2",
            open = "1",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "nd",
        name = "outState",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.6.2"] =
    {
        oidLength = "5",
        ubusType = "nd",
        i2c_addr = "0",
        name = "comfortStartStatus",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.1.2"] =
    {
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        name = "autoRestart",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.8"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpTemperature",
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.5"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "no",
        i2c_addr = "0",
        valueType = "DisplayString",
        ubusType = "i2c",
        name = "portSfpOui",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.1.2.1"] =
    {
        nodetype = "table",
        oidLength = "5",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "autoRestartTable",
    },
    ["1.3.6.1.4.1.42019.3.2.1.2.1.1.9"] =
    {
        valueType = "INTEGER",
        nodetype = "scalar",
        oidLength = "7",
        ubusType = "ar_config",
        i2c_addr = "0",
        isZero = "no",
        name = "autoReStartTimeOffMin",
    },
    ["1.3.6.1.4.1.42019.3.2.2.1"] =
    {
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        name = "upsStatus",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.4.2.3"] =
    {
        oidLength = "3",
        ubusType = "nd",
        i2c_addr = "0",
        name = "outputTeleport",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.6.2.1.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "8",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "csPortIndex",
    },
    ["1.3.6.1.4.1.42019.3.2.2.8.6"] =
    {
        valueType = "INTEGER",
        nodetype = "scalar",
        oidLength = "5",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "sensorHumidityMin",
    },
    ["1.3.6.1.4.1.42019.3.2.2.6.2.1.1"] =
    {
        nodetype = "row",
        oidLength = "7",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "comfortStartStatusEntry",
    },
    ["1.3.6.1.4.1.42019.4.2.3.1.1"] =
    {
        nodetype = "row",
        oidLength = "5",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "outputTeleportEntry",
    },
    ["1.3.6.1.4.1.42019.3.2.2.2.1.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "inputIndex",
    },
    ["1.3.6.1.4.1.42019.3.2.2.8.2"] =
    {
        valueType = "INTEGER",
        nodetype = "scalar",
        oidLength = "5",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "sensorTemperature",
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.2"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpPresent",
    },
    ["1.3.6.1.4.1.42019.3.2.2.1.4"] =
    {
        valueType = "INTEGER",
        nodetype = "scalar",
        oidLength = "5",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "upsBatteryTime",
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1"] =
    {
        nodetype = "row",
        oidLength = "6",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "sfpStatusEntry",
    },
    ["1.3.6.1.4.1.42019.3.2.1.2.1.1.8"] =
    {
        valueType = "INTEGER",
        nodetype = "scalar",
        oidLength = "7",
        ubusType = "ar_config",
        i2c_addr = "0",
        isZero = "no",
        name = "autoReStartTimeOffHour",
    },
    ["1.3.6.1.4.1.42019.3.2.1.2.1.1.2"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "yes",
        enum  = {
            time = "4",
            ping = "2",
            link = "1",
            disabled = "0",
            speed = "3",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "ar_config",
        name = "autoRstMode",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.3"] =
    {
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        name = "fwStatus",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.2.5.1.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "poe_status",
        i2c_addr = "0",
        isZero = "no",
        name = "portPoeStatusIndex",
    },
    ---------------------  1.3.6.1.4.1.42019.3.2 - found
    ["1.3.6.1.4.1.42019.3.2"] =
    {
        oidLength = "2",
        ubusType = "nd",
        i2c_addr = "0",
        name = "psw",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.2.6.2.1.1.2"] =
    {
        nodetype = "column",
        oidLength = "8",
        isEnum = "yes",
        enum  = {
            processing = "2",
            normal = "1",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "nd",
        name = "csPortStatus",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.4"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "no",
        i2c_addr = "0",
        valueType = "DisplayString",
        ubusType = "i2c",
        name = "portSfpVendor",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3"] =
    {
        oidLength = "1",
        ubusType = "nd",
        i2c_addr = "0",
        name = "switch",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.2.5.1.1.3"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "poe_status",
        i2c_addr = "0",
        isZero = "no",
        name = "portPoeStatusPower",
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.7"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "no",
        i2c_addr = "0",
        valueType = "DisplayString",
        ubusType = "i2c",
        name = "portSfpRevision",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.8.1"] =
    {
        nodetype = "scalar",
        oidLength = "5",
        isEnum = "yes",
        enum  = {
            connected = "1",
            disconnected = "2",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "i2c",
        name = "sensorConnected",
        isZero = "isZero",
    },
    ["1.3.6.1.4.1.42019.3.2.1.1.1"] =
    {
        nodetype = "scalar",
        oidLength = "5",
        isEnum = "no",
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "nd",
        name = "comfortStartTime",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.1.2.1.1.6"] =
    {
        valueType = "INTEGER",
        nodetype = "scalar",
        oidLength = "7",
        ubusType = "ar_config",
        i2c_addr = "0",
        isZero = "no",
        name = "autoReStartTimeOnHour",
    },
    ["1.3.6.1.4.1.42019.3.2.2.8.7"] =
    {
        valueType = "INTEGER",
        nodetype = "scalar",
        oidLength = "5",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "sensorHumidityMax",
    },
    ["1.3.6.1.4.1.42019.3.2.2.8.4"] =
    {
        valueType = "INTEGER",
        nodetype = "scalar",
        oidLength = "5",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "sensorTemperatureMin",
    },
    ["1.3.6.1.4.1.42019.3.2.2.8"] =
    {
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        name = "sensorEntry",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.1.2.1.1.7"] =
    {
        valueType = "INTEGER",
        nodetype = "scalar",
        oidLength = "7",
        ubusType = "ar_config",
        i2c_addr = "0",
        isZero = "no",
        name = "autoReStartTimeOnMin",
    },
    ["1.3.6.1.4.1.42019.3.2.1.2.1.1.4"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "ar_config",
        i2c_addr = "0",
        isZero = "no",
        name = "autoRstSpeedDown",
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.11"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpTxOutPower",
    },
    ["1.3.6.1.4.1.42019.3.2.2.8.5"] =
    {
        valueType = "INTEGER",
        nodetype = "scalar",
        oidLength = "5",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "sensorTemperatureMax",
    },
    ["1.3.6.1.4.1.42019.4.2.2.1"] =
    {
        nodetype = "table",
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "inputStatusTableTLP",
    },
    ["1.3.6.1.4.1.42019.3.2.1.1.2.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "comfStIndex",
    },
    ["1.3.6.1.4.1.42019.3.2.1.4"] =
    {
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        name = "outStatePSW",
        isZero = "no",
        nodetype = "list"
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.14"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpRxOutPowerDb",
    },
    ["1.3.6.1.4.1.42019"] =
    {
        oidLength = "0",
        ubusType = "nd",
        i2c_addr = "0",
        name = "forttelecomMIB",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.4.2.3.1.1.1"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "6",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "outIndex",
    },
    ["1.3.6.1.4.1.42019.3.2.2.2.1.1.2"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "yes",
        enum  = {
            build_in = "1",
            plc = "2",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "i2c",
        name = "inputType",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.2.1.1"] =
    {
        nodetype = "row",
        oidLength = "6",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "inputStatusEntry",
    },
    ["1.3.6.1.4.1.42019.4.2.3.1"] =
    {
        nodetype = "table",
        oidLength = "4",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "outputTeleportTable",
    },
    ["1.3.6.1.4.1.42019.3.2.1.1.2.1.2"] =
    {
        nodetype = "column",
        oidLength = "7",
        isEnum = "yes",
        enum  = {
            enabled = "1",
            disabled = "2",
        },
        i2c_addr = "0",
        valueType = "INTEGER",
        ubusType = "nd",
        name = "comfStState",
        isZero = "no",
    },
    ["1.3.6.1.4.1.42019.3.2.2.7.1.1.13"] =
    {
        valueType = "INTEGER",
        nodetype = "column",
        oidLength = "7",
        ubusType = "i2c",
        i2c_addr = "0",
        isZero = "no",
        name = "portSfpRxOutPower",
    },
    ["1.3.6.1.4.1.42019.3.2.2.6.2.1"] =
    {
        nodetype = "table",
        oidLength = "6",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "comfortStartStatusTable",
    },
    ["1.3.6.1.4.1.42019.3.2.2.5.1.1"] =
    {
        nodetype = "row",
        oidLength = "6",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "poeStatusEntry",
    },
    ["1.3.6.1.4.1.42019.3.2.2.6.1.1.1"] =
    {
        nodetype = "row",
        oidLength = "7",
        ubusType = "nd",
        i2c_addr = "0",
        isZero = "no",
        name = "autoRestartErrorsEntry",
    },
}

return snmp_base

