#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/6/24 2:58 PM
---

local tf        = require "tf_module"
local utilities = require "tf_utilities"
local tf_snmp   = require "tf_snmp_module"
local log       = require "tf_log"
local ar        = require "autorestart_module"

-- mib_json_path = "/etc/tf_statistics/mib/FORT-TELECOM-MIB.json"

function ar_showConfig()
    local resConfig = {}
    cmd = "ubus call uci get '{\"config\":\"tf_autorestart\"}'"
    resConfig = tf.collectJsonTable(cmd)
    return resConfig
end

if arg[1] == "config" then
    ar.showConfig()
elseif arg[1] == "status" then
    ar.showStatus()
end
