---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/14/24 11:06 AM
---

local log_module = {}

function log_module:new(fileName, OidName, res, portNum, inputOid, modifiedOid)

    local data = {}
    data.fileName = fileName
    data.OidName = OidName
    data.res = res
    data.portNum = portNum
    data.inputOid = inputOid
    data.modifiedOid = modifiedOid

    function data:WritelogOid()
        local file = io.open(self.fileName, "w")
        file:write("name " .. self.OidName .. "\n")
        file:write("index " .. self.portNum .. "\n")
        file:write("res --->>>  " .. self.res .. "\n")
        file:write("inputOid = " .. self.inputOid .. "\n")
        file:write("modifiedOid " .. self.modifiedOid .. "\n")
        file:close()
    end

    function log_module.WritelogArg(logFile, arguments)
        local file = io.open(logFile, "w")
        file:write("arg Num = " .. #arguments .. "\n")
        for argindex = 1, #arguments do
            file:write("arg " .. argindex .. " = " .. arguments[argindex] .. "\n")
        end
    end
    setmetatable(data, self)
    self.__index = self; return data
end

return log_module


