---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/12/24 12:16 PM
---
local tf = require "tf_module"

local tf_poe_module = {}

tf_poe_module.portsEnum = {
    priority    = "priority",
    status      = "status",
    consumption = "consumption"
}

tf_poe_module.statusEnum = {
    ["Searching"] = 2,
    ["Delivering power"] = 1
}

tf_poe_module.enum = {
    firmware    = "firmware",
    mcu         = "mcu",
    budget      = "budget",
    consumption = "consumption",
    ports       = "ports"
}

tf_poe_module.portPoE_config =
{
    portPoeState = { "poe", "PoE State: " }
}

function tf_poe_module.getPoeStatusInfo()
    local jsonPoeInfo = tf.collectJsonTable("ubus call poe info")
    return jsonPoeInfo
end

function tf_poe_module.getPoeSateInfo(portNum)
    local resPoeState = {}
    local cmd = ""
    if portNum == "all" then
        cmd = "ubus call uci get '{\"config\":\"port\"}'"
    else
        cmd = "ubus call uci get '{\"config\":\"port\", \"section\":\"" .. portNum .. "\"}'"
    end
    --print("cmd = " .. cmd)
    resPoeState = tf.collectJsonTable(cmd)
    return resPoeState
end

return tf_poe_module




