---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 3/12/24 10:55 AM
---

tf_utilities = {}

function tf_utilities.countDots(str)
    local count = 0
    for char in str:gmatch(".") do
        if char == '.' then
            count = count + 1
        end
    end
    return count
end

function tf_utilities.separateLettersAndNumbers(inputString)
    local letters = ""
    local numbers = ""
    for i = 1, #inputString do
        local char = inputString:sub(i, i)
        if tonumber(char) ~= nil then
            numbers = numbers .. char
        else
            letters = letters .. char
        end
    end
    return letters, tonumber(numbers)
end

function modifyString(inputString)
    local startIndex = string.find(inputString, "%.", 1) + 1
    local endIndex = string.len(inputString) - 1
    local modifiedString = string.sub(inputString, startIndex, endIndex)

    return modifiedString
end

local originalString = ".1.3.6.1.4.1.42019.3.2.2.2.1.1.3.2.5"
local modifiedString = modifyString(originalString)



return tf_utilities
