#!/usr/bin/lua

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sheverdin.
--- DateTime: 4/26/24 4:11 PM
---


function main_handler()
    print(arg[2])
    print("INTEGER")
    print(10)
end

main_handler()